import {Inter} from "next/font/google";
import "./globals.css";
import ApolloClientProvider from "/Users/a111/Desktop/graphql-test/graphql-test/src/lib/ApolloClientProvider.js";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ApolloClientProvider>
            {children}
        </ApolloClientProvider>
        </body>
        </html>
    );
}
